In [1]:
import pandas as pd
import nltk
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize
import string
import ssl

In [2]:
try:
    _create_unverified_https_context = ssl._create_unverified_context
except AttributeError:
    pass
else:
    ssl._create_default_https_context = _create_unverified_https_context

In [3]:
nltk.download('stopwords')
nltk.download('punkt')
nltk.download('punkt_tab')

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\conta\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\conta\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package punkt_tab to
[nltk_data]     C:\Users\conta\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!

True

In [4]:
print("Verificando recursos do NLTK:")
print("punkt:", nltk.data.find('tokenizers/punkt'))
print("stopwords:", nltk.data.find('corpora/stopwords'))

Verificando recursos do NLTK:
punkt: C:\Users\conta\AppData\Roaming\nltk_data\tokenizers\punkt
stopwords: C:\Users\conta\AppData\Roaming\nltk_data\corpora\stopwords

In [5]:
stop_words = set(stopwords.words('portuguese'))

In [6]:
df = pd.read_excel('C:/Users/conta/OneDrive/Desktop/Filtro Palavras/PROGRAMAÇÃO_ARTIGOS_CONGRESSO_CONSAD_2025.xlsx')

In [7]:
df.head()

,Id do trabalho,Área temática,Título,Nome dos autores (separado por vírgula),Código do resumo,Data e Horário de Apresentação,Sala
0,1201708,CULTURA ORGANIZACIONAL E A GESTÃO ESTRATÉGICA ...,A GESTÃO BUROCRÁTICA E SEUS EFEITOS NO CLIMA O...,"KÁRITA ALLEN,PAMELA NATIELLE BASILIO E SILVA,F...",1128006,26 de Agosto - 17h00,Sala 4
1,1207428,CULTURA ORGANIZACIONAL E A GESTÃO ESTRATÉGICA ...,"CULTURA ORGANIZACIONAL, VALORIZAÇÃO DE SERVIDO...","LUCIANO ARAUJO LIMA,NADJANARA LOPES DE ABREU A...",1119056,26 de Agosto - 17h00,Sala 5
2,1208275,CULTURA ORGANIZACIONAL E A GESTÃO ESTRATÉGICA ...,ECOAR - EDUCAÇÃO CORPORATIVA E APRENDIZAGEM EM...,"VANESSA DE OLIVEIRA SANTANA DERVINIS,FÁBIO DER...",1130109,27 de Agosto - 16h10,Sala 8
3,1211448,CULTURA ORGANIZACIONAL E A GESTÃO ESTRATÉGICA ...,PODCAST COMO ESTRATÉGIA INOVADORA DE COMUNICAÇ...,"REBECA RÊGO PEDROSA COSTA,HERLANE SUELE ALVES ...",1122770,26 de Agosto - 09h00,-
4,1215994,CULTURA ORGANIZACIONAL E A GESTÃO ESTRATÉGICA ...,"ASCENSÃO, PERMANÊNCIA E INFLUÊNCIA: O CASO DAS...","MARCELA CARVALHO,GUSTAVO MOREIRA TAVARES",1123635,27 de Agosto - 16h10,Sala 8

In [8]:
df1 = df[['Área temática', 'Título', 'Data e Horário de Apresentação']]

In [9]:
df1.head()

,Área temática,Título,Data e Horário de Apresentação
0,CULTURA ORGANIZACIONAL E A GESTÃO ESTRATÉGICA ...,A GESTÃO BUROCRÁTICA E SEUS EFEITOS NO CLIMA O...,26 de Agosto - 17h00
1,CULTURA ORGANIZACIONAL E A GESTÃO ESTRATÉGICA ...,"CULTURA ORGANIZACIONAL, VALORIZAÇÃO DE SERVIDO...",26 de Agosto - 17h00
2,CULTURA ORGANIZACIONAL E A GESTÃO ESTRATÉGICA ...,ECOAR - EDUCAÇÃO CORPORATIVA E APRENDIZAGEM EM...,27 de Agosto - 16h10
3,CULTURA ORGANIZACIONAL E A GESTÃO ESTRATÉGICA ...,PODCAST COMO ESTRATÉGIA INOVADORA DE COMUNICAÇ...,26 de Agosto - 09h00
4,CULTURA ORGANIZACIONAL E A GESTÃO ESTRATÉGICA ...,"ASCENSÃO, PERMANÊNCIA E INFLUÊNCIA: O CASO DAS...",27 de Agosto - 16h10

In [10]:
df1 = df1.set_index('Data e Horário de Apresentação')

In [11]:
df1.head()

,Área temática,Título
Data e Horário de Apresentação,,
26 de Agosto - 17h00,CULTURA ORGANIZACIONAL E A GESTÃO ESTRATÉGICA ...,A GESTÃO BUROCRÁTICA E SEUS EFEITOS NO CLIMA O...
26 de Agosto - 17h00,CULTURA ORGANIZACIONAL E A GESTÃO ESTRATÉGICA ...,"CULTURA ORGANIZACIONAL, VALORIZAÇÃO DE SERVIDO..."
27 de Agosto - 16h10,CULTURA ORGANIZACIONAL E A GESTÃO ESTRATÉGICA ...,ECOAR - EDUCAÇÃO CORPORATIVA E APRENDIZAGEM EM...
26 de Agosto - 09h00,CULTURA ORGANIZACIONAL E A GESTÃO ESTRATÉGICA ...,PODCAST COMO ESTRATÉGIA INOVADORA DE COMUNICAÇ...
27 de Agosto - 16h10,CULTURA ORGANIZACIONAL E A GESTÃO ESTRATÉGICA ...,"ASCENSÃO, PERMANÊNCIA E INFLUÊNCIA: O CASO DAS..."

In [12]:
cont_area_tematica = df1['Área temática'].value_counts()
print("Valores únicos e suas frequências:")
print(cont_area_tematica)

Valores únicos e suas frequências:
Área temática
CULTURA ORGANIZACIONAL E A GESTÃO ESTRATÉGICA DE PESSOAS: UM CAMINHO PARA EXCELÊNCIA    70
REINVENTANDO O ESTADO: DESAFIOS E OPORTUNIDADES                                         39
INVESTIMENTOS E GESTÃO DE ATIVOS                                                        37
GOVERNO DIGITAL E TRANSPARÊNCIA: CONSTRUINDO UM FUTURO MAIS ABERTO                      36
GESTÃO EFICIENTE E SUSTENTÁVEL: PRÁTICAS E DESAFIOS NA ADMINISTRAÇÃO PÚBLICA            30
INTELIGÊNCIA ARTIFICIAL E O FUTURO DA GESTÃO PÚBLICA                                    28
Name: count, dtype: int64

In [13]:
def limpar_texto(texto):
    try:
        texto = str(texto)
        texto = texto.lower()
        texto = ''.join([char for char in texto if char not in string.punctuation])
        tokens = word_tokenize(texto)
        palavras_filtradas = [palavra for palavra in tokens if palavra not in stop_words and len(palavra) > 2]
        return ' '.join(palavras_filtradas)
    except Exception as e:
        print(f"Erro ao processar texto: {texto}")
        print(f"Erro: {str(e)}")
        return ""

df1['Palavras_Chave'] = df1['Título'].apply(limpar_texto)

In [14]:
print("Primeiros 5 títulos com suas palavras-chave:")
for titulo, palavras_chave in zip(df1['Título'].head(), df1['Palavras_Chave'].head()):
    print(f"\nTítulo original:\n{titulo}")
    print(f"Palavras-chave:\n{palavras_chave}")

Primeiros 5 títulos com suas palavras-chave:

Título original:
A GESTÃO BUROCRÁTICA E SEUS EFEITOS NO CLIMA ORGANIZACIONAL: UM ESTUDO EXPLORATÓRIO NA 1ª CIA DO DÉCIMO NONO BATALHÃO DE POLÍCIA MILITAR METROPOLITANO DE SÃO PAULO
Palavras-chave:
gestão burocrática efeitos clima organizacional estudo exploratório cia décimo nono batalhão polícia militar metropolitano paulo

Título original:
CULTURA ORGANIZACIONAL, VALORIZAÇÃO DE SERVIDORES E DESCENTRALIZAÇÃO: CAMINHOS PARA A INOVAÇÃO NA GESTÃO PÚBLICA E FORTALECIMENTO DA GOVERNANÇA INSTITUCIONAL
Palavras-chave:
cultura organizacional valorização servidores descentralização caminhos inovação gestão pública fortalecimento governança institucional

Título original:
ECOAR - EDUCAÇÃO CORPORATIVA E APRENDIZAGEM EM REDE: UMA ESTRATÉGIA PARA A DIFUSÃO DO CONHECIMENTO EM ORGANIZAÇÕES PÚBLICAS MULTI-INSTITUCIONAIS
Palavras-chave:
ecoar educação corporativa aprendizagem rede estratégia difusão conhecimento organizações públicas multiinstitucionais

Título original:
PODCAST COMO ESTRATÉGIA INOVADORA DE COMUNICAÇÃO E APRENDIZAGEM EM UMA SECRETARIA DE PLANEJAMENTO E GESTÃO
Palavras-chave:
podcast estratégia inovadora comunicação aprendizagem secretaria planejamento gestão

Título original:
ASCENSÃO, PERMANÊNCIA E INFLUÊNCIA: O CASO DAS LÍDERES MULHERES NO GOVERNO FEDERAL BRASILEIRO
Palavras-chave:
ascensão permanência influência caso líderes mulheres governo federal brasileiro

In [15]:
df1.head()

,Área temática,Título,Palavras_Chave
Data e Horário de Apresentação,,,
26 de Agosto - 17h00,CULTURA ORGANIZACIONAL E A GESTÃO ESTRATÉGICA ...,A GESTÃO BUROCRÁTICA E SEUS EFEITOS NO CLIMA O...,gestão burocrática efeitos clima organizaciona...
26 de Agosto - 17h00,CULTURA ORGANIZACIONAL E A GESTÃO ESTRATÉGICA ...,"CULTURA ORGANIZACIONAL, VALORIZAÇÃO DE SERVIDO...",cultura organizacional valorização servidores ...
27 de Agosto - 16h10,CULTURA ORGANIZACIONAL E A GESTÃO ESTRATÉGICA ...,ECOAR - EDUCAÇÃO CORPORATIVA E APRENDIZAGEM EM...,ecoar educação corporativa aprendizagem rede e...
26 de Agosto - 09h00,CULTURA ORGANIZACIONAL E A GESTÃO ESTRATÉGICA ...,PODCAST COMO ESTRATÉGIA INOVADORA DE COMUNICAÇ...,podcast estratégia inovadora comunicação apren...
27 de Agosto - 16h10,CULTURA ORGANIZACIONAL E A GESTÃO ESTRATÉGICA ...,"ASCENSÃO, PERMANÊNCIA E INFLUÊNCIA: O CASO DAS...",ascensão permanência influência caso líderes m...

In [16]:
df1.to_excel('dados_palavras_chave.xlsx')

In [17]:
palavras_series = pd.Series(' '.join(df1['Palavras_Chave']).split())

frequencia_palavras = palavras_series.value_counts()

df_palavras = pd.DataFrame({
    'Palavra': frequencia_palavras.index,
    'Frequência': frequencia_palavras.values
})

print("\nAnálise detalhada das palavras mais frequentes:")
print(df_palavras.head(10))

df_palavras.to_excel('analise_palavras_frequentes.xlsx', index=False)

Análise detalhada das palavras mais frequentes:
         Palavra  Frequência
0         gestão          78
1        pública          53
2        público          33
3       públicos          31
4       inovação          29
5        digital          27
6          setor          21
7     eficiência          21
8     estratégia          19
9  transformação          18